export const countries = [
    { code: "AF", name: "Afghanistan" },
    { code: "AL", name: "Albanie" },
    { code: "DZ", name: "Algérie" },
    { code: "AS", name: "Samoa américaines" },
    { code: "AD", name: "Andorre" },
    { code: "AO", name: "Angola" },
    { code: "AR", name: "Argentine" },
    { code: "AM", name: "Arménie" },
    { code: "AU", name: "Australie" },
    { code: "AT", name: "Autriche" },
    { code: "AZ", name: "Azerbaïdjan" },
    { code: "BH", name: "Bahreïn" },
    { code: "BD", name: "Bangladesh" },
    { code: "BY", name: "Biélorussie" },
    { code: "BE", name: "Belgique" },
    { code: "BR", name: "Brésil" },
    { code: "CA", name: "Canada" },
    { code: "CN", name: "Chine" },
    { code: "CO", name: "Colombie" },
    { code: "HR", name: "Croatie" },
    { code: "CU", name: "Cuba" },
    { code: "CY", name: "Chypre" },
    { code: "CZ", name: "République tchèque" },
    { code: "DK", name: "Danemark" },
    { code: "EG", name: "Égypte" },
    { code: "EE", name: "Estonie" },
    { code: "FI", name: "Finlande" },
    { code: "FR", name: "France" },
    { code: "DE", name: "Allemagne" },
    { code: "GR", name: "Grèce" },
    { code: "HU", name: "Hongrie" },
    { code: "IS", name: "Islande" },
    { code: "IN", name: "Inde" },
    { code: "ID", name: "Indonésie" },
    { code: "IR", name: "Iran" },
    { code: "IQ", name: "Irak" },
    { code: "IE", name: "Irlande" },
    { code: "IL", name: "Israël" },
    { code: "IT", name: "Italie" },
    { code: "JP", name: "Japon" },
    { code: "JO", name: "Jordanie" },
    { code: "KZ", name: "Kazakhstan" },
    { code: "KE", name: "Kenya" },
    { code: "KW", name: "Koweït" },
    { code: "LV", name: "Lettonie" },
    { code: "LB", name: "Liban" },
    { code: "LT", name: "Lituanie" },
    { code: "LU", name: "Luxembourg" },
    { code: "MY", name: "Malaisie" },
    { code: "MX", name: "Mexique" },
    { code: "MA", name: "Maroc" },
    { code: "NL", name: "Pays-Bas" },
    { code: "NZ", name: "Nouvelle-Zélande" },
    { code: "NG", name: "Nigeria" },
    { code: "NO", name: "Norvège" },
    { code: "PK", name: "Pakistan" },
    { code: "PE", name: "Pérou" },
    { code: "PH", name: "Philippines" },
    { code: "PL", name: "Pologne" },
    { code: "PT", name: "Portugal" },
    { code: "QA", name: "Qatar" },
    { code: "RO", name: "Roumanie" },
    { code: "RU", name: "Russie" },
    { code: "SA", name: "Arabie Saoudite" },
    { code: "RS", name: "Serbie" },
    { code: "SG", name: "Singapour" },
    { code: "SK", name: "Slovaquie" },
    { code: "SI", name: "Slovénie" },
    { code: "ZA", name: "Afrique du Sud" },
    { code: "KR", name: "Corée du Sud" },
    { code: "ES", name: "Espagne" },
    { code: "SE", name: "Suède" },
    { code: "CH", name: "Suisse" },
    { code: "TH", name: "Thaïlande" },
    { code: "TR", name: "Turquie" },
    { code: "UA", name: "Ukraine" },
    { code: "AE", name: "Émirats arabes unis" },
    { code: "GB", name: "Royaume-Uni" },
    { code: "US", name: "États-Unis" },
    { code: "VN", name: "Vietnam" },
    { code: "YE", name: "Yémen" },
    { code: "ZM", name: "Zambie" },
    { code: "ZW", name: "Zimbabwe" }
  ];
  